# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4
#tri
trigger:
- dev
##########################build#############################
stages:
- stage: BuildApp
  displayName: Building App
  jobs:
  - job: Build
    pool:
      name: Default
    variables:
    - name: RestoreBuildProjects
      value: '**/*.csproj'
    - name: TestProjects
      value: '**/*[Tt]ests/*.csproj'

    steps:
      - task: DotNetCoreCLI@2
        displayName: Restore
        inputs:
          command: restore
          projects: $(RestoreBuildProjects)
      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          projects: $(RestoreBuildProjects)
        
      - task: DotNetCoreCLI@2
        displayName: Test
        inputs:
          command: test
          projects: $(TestProjects)
      
      - task: DotNetCoreCLI@2
        displayName: Publish
        inputs:
          command: 'publish'
          publishWebProjects: true
          arguments: ' --output $(build.artifactstagingdirectory)'
          zipAfterPublish: false
          modifyOutputPath: false
 
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'

###########################deploy to dev###########################################
- stage: DeployToDev
  displayName: deploy dev stage
  jobs:
  - job: Deploy
    pool:
      name: Default
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(Pipeline.Workspace)'
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure for Students(6536b5fd-c0ab-4e5a-bc8d-7ca256fdde1a)'
        appType: 'webApp'
        WebAppName: 'dotnet-dev121'
        packageForLinux: '$(Pipeline.Workspace)/drop'

    - task: CreatePullRequest@1
      inputs:
        repoType: 'Azure DevOps'
        repositorySelector: 'currentBuild'
        sourceBranch: '$(Build.SourceBranch)'
        targetBranch: 'master'
        title: 'dev to master'

#############deploy to qa#############################################################
- stage: DeployToQA
  displayName: deploy qa stage
  jobs:
  - deployment : Deploy
    environment: qa
    pool:
      name: Default
    strategy:
      runOnce:
        deploy:
          steps:  
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(Pipeline.Workspace)'
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Azure for Students(6536b5fd-c0ab-4e5a-bc8d-7ca256fdde1a)'
              appType: 'webApp'
              WebAppName: 'dotnetqaa121'
              packageForLinux: '$(Pipeline.Workspace)/drop'

###################deploy to prod###############################
- stage: DeployToProd
  displayName: deploy prod stage
  jobs:
  - deployment : Deploy
    environment: prod
    pool:
      name: Default
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(Pipeline.Workspace)'
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Azure for Students(6536b5fd-c0ab-4e5a-bc8d-7ca256fdde1a)'
              appType: 'webApp'
              WebAppName: 'dotnetapp1211'
              packageForLinux: '$(Pipeline.Workspace)/drop'
